actions_list = [
    "拿东西",
    "转头",
    "说谢谢",
    "谈论钱",
    "说明星名",
    "说不知道",
    "道歉",
    "击掌",
    "鼓掌",
    "点头",
    "说好听",
    "拒绝表演",
    "靠椅子",
    "抖腿",
    "摇头",
    "扶眼镜",
    "说不是",
    "笑",
    "沉默十秒",
    "吃东西",
    "喝水",
    "唱歌",
    "大声说话",
    "说好的",
    "说可以",
    "说觉得",
    "站起来",
    "翘二郎腿",
    "说数字",
    "看时间",
    "谈论时间",
    "猜拳",
    "摇头",
    "夸别人",
    "拒绝别人",
    "说哪里",
    "扶额",
    "整理衣服",
    "说名字",
    "说没有",
    "回头看",
    "递东西",
    "提问",
    "拍打别人",
    "回答问题",
    "手指别人",
    "说好难",
    "说哦",
    "嘲笑别人",
    "瞪眼",
    "摸后脑勺",
    "说开始",
    "说不要",
    "捂嘴",
    "说回家",
    "站起来",
    "推开",
    "挥手",
    "称赞别人",
    "向上看",
    "大笑",
    "说为什么",
    "拿杯子",
    "怀疑别人",
    "回忆",
    "说别动",
    "说考试",
    "说年龄",
    "说英文",
    "握拳",
    "摸嘴唇",
    "扶眼镜",
    "接东西",
    "说加油",
    "说脏话",
    "打哈欠",
    "说朋友",
    "模仿别人",
    "说菜名",
    "说该谁了",
    "谈论对象",
    "使眼色",
    "说我不说",
    "说不知道",
    "讨论玩法",
    "手放腿上",
    "说没事",
    "打赌",
    "摸头发",
    "摸鼻子",
    "说明天",
    "说昨天",
    "说你",
    "说我",
    "说他",
    "表示同意",
    "握拳",
    "说\"ok\"",
    "笑",
    "用手指",
    "夸对方",
    "摸头（发）",
    "转头",
    "露齿笑",
    "唱歌",
    "哈哈大笑",
    "看窗外",
    "眯眼睛",
    "抬胳膊",
    "闭眼睛",
    "发呆",
    "叹气",
    "吐槽",
    "抖腿",
    "伸开手臂",
    "移动屁股",
    "放大鼻孔",
    "说一个抖音里的梗",
    "说英文",
    "说一个人的名字",
    "说一个食物",
    "说另一个人的名字",
    "说一个学科的名字",
    "说一个动物的名字",
    "说如果",
    "说语气词",
    "说人名",
    "说任何否定词",
    "说任何肯定词",
    "介绍故乡",
    "重复一句我说的或者你说的",
    "思考",
    "问问题",
    "回答问题",
    "回避问题",
    "询问",
    "骂人",
    "做比较",
    "吐槽游戏题目难",
    "夸对方",
    "做鬼脸",
    "嘟嘴",
    "碰脸部一个位置",
    "惊讶地张大嘴（说话不算）",
    "摇头晃脑",
    "向下看",
    "向上看",
    "犹豫",
    "碰到腿",
    "露牙笑",
    "放屁",
    "发出怪声",
    "说一个地名"
]

actions_list_english = [
    "Pick something up",
    "Turn head",
    "Say thank you",
    "Talk about money",
    "Mention celebrity name",
    "Say I don't know",
    "Apologize",
    "High five",
    "Clap",
    "Nod",
    "Say it sounds good",
    "Refuse to perform",
    "Lean against chair",
    "Shake leg",
    "Shake head",
    "Adjust glasses",
    "Say no",
    "Laugh",
    "Silent for ten seconds",
    "Eat something",
    "Drink water",
    "Sing",
    "Speak loudly",
    "Say OK",
    "Say it's fine",
    "Say I think",
    "Stand up",
    "Cross legs",
    "Say a number",
    "Check the time",
    "Talk about time",
    "Play rock-paper-scissors",
    "Shake head",
    "Compliment someone",
    "Reject someone",
    "Say where",
    "Facepalm",
    "Adjust clothing",
    "Say someone's name",
    "Say no/not have",
    "Look back",
    "Pass something",
    "Ask a question",
    "Pat someone",
    "Answer a question",
    "Point at someone",
    "Say it's difficult",
    "Say oh",
    "Laugh at someone",
    "Glare",
    "Touch back of head",
    "Say start",
    "Say no/don't want",
    "Cover mouth",
    "Say go home",
    "Stand up",
    "Push away",
    "Wave hand",
    "Praise someone",
    "Look up",
    "Laugh loudly",
    "Say why",
    "Pick up a cup",
    "Suspect someone",
    "Recall something",
    "Say don't move",
    "Mention an exam",
    "State age",
    "Speak English",
    "Clench fist",
    "Touch lips",
    "Adjust glasses",
    "Receive something",
    "Say come on",
    "Swear",
    "Yawn",
    "Mention friend",
    "Imitate someone",
    "Name a dish",
    "Say whose turn",
    "Talk about partner",
    "Make eye contact",
    "Say I won't tell",
    "Say I don't know",
    "Discuss rules/how to play",
    "Place hands on lap",
    "Say it's okay",
    "Make a bet",
    "Touch hair",
    "Touch nose",
    "Mention tomorrow",
    "Mention yesterday",
    "Say you",
    "Say me",
    "Say him",
    "Express agreement",
    "Clench fist",
    "Say 'OK'",
    "Laugh",
    "Use fingers",
    "Praise someone",
    "Touch head (hair)",
    "Turn head",
    "Show teeth while smiling",
    "Sing",
    "Laugh out loud",
    "Look out the window",
    "Squint",
    "Raise arm",
    "Close eyes",
    "Zone out",
    "Sigh",
    "Complain",
    "Shake leg",
    "Stretch out arms",
    "Move hips",
    "Flare nostrils",
    "Say a trending phrase from TikTok",
    "Speak English",
    "Say someone's name",
    "Say a food name",
    "Say another person's name",
    "Say a subject name",
    "Say an animal name",
    "Say 'if'",
    "Say an interjection",
    "Mention a person's name",
    "Say any negative word",
    "Say any positive word",
    "Introduce your hometown",
    "Repeat a sentence I or you said",
    "Think",
    "Ask a question",
    "Answer a question",
    "Avoid answering a question",
    "Inquire",
    "Swear",
    "Make a comparison",
    "Complain about the difficulty of the game",
    "Praise someone",
    "Make a funny face",
    "Pout",
    "Touch a part of your face",
    "Open mouth wide in surprise (without speaking)",
    "Shake head side to side",
    "Look down",
    "Look up",
    "Hesitate",
    "Touch your leg",
    "Smile with teeth showing",
    "Fart",
    "Make a weird noise",
    "Mention a place"
]
